CREATE TABLE zones (
	id int(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	sistema VARCHAR(255),
	region VARCHAR(255),
	zona VARCHAR(255)
);

CREATE TABLE nodes (
	-- id int(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nodo_id VARCHAR(30) NOT NULL PRIMARY KEY,
	nombre VARCHAR(255),
	zone_id int(11) UNSIGNED NOT NULL,
	FOREIGN KEY(zone_id) REFERENCES zones(id)
);


CREATE TABLE precios (
	id int(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	fecha DATE NOT NULL,
	hora TINYINT UNSIGNED NOT NULL,
	node_id VARCHAR(30) NOT NULL,
	pml DECIMAL(19,4),
	energia DECIMAL(19,4),
	perdidas DECIMAL(19,4),
	congestion DECIMAL(19,4),
	INDEX `date_index` (fecha),
	FOREIGN KEY(node_id) REFERENCES nodes(nodo_id)
);

CREATE TABLE demanda (
	id int(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	fecha DATE NOT NULL,
	zdc_id int(11) UNSIGNED NOT NULL,
	hora TINYINT UNSIGNED NOT NULL,
	cdm DECIMAL(19,4),
	cim DECIMAL(19,4),
	eta DECIMAL(19,4),
	INDEX date_index (fecha),
	FOREIGN KEY(zdc_id) REFERENCES zones(id)
);


-- ALTER TABLE demanda ADD fecha DATE NOT NULL AFTER `id`;
