CREATE TABLE precios (
	id int(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	fecha DATE NOT NULL,
	hora TINYINT UNSIGNED NOT NULL,
	node_id int(11) UNSIGNED NOT NULL,
	pml DECIMAL(19,4),
	energia DECIMAL(19,4),
	perdidas DECIMAL(19,4),
	congestion DECIMAL(19,4),
	FOREIGN KEY node_id REFERENCES nodes(id)
);

CREATE TABLE demanda (
	id int(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	zdc_id int(11) UNSIGNED NOT NULL,
	hora TINYINT UNSIGNED NOT NULL,
	cdm DECIMAL(5,4),
	cim DECIMAL(5,4),
	eta DECIMAL(5,4),
	FOREIGN KEY zdc_id REFERENCES zones(id)
);


CREATE TABLE nodes (
	id int(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	nodo_id
);

CREATE TABLE zones (
	id int(11) UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
	name
);
